### ISSUE TITLE
Persisting a new contact in mysql

### ISSUE THREAD

**Issue by brunocantisano** [ethnchao/docker-nagios#3]
I started the container with --enable-ndo --create-db, so the database were created. After that I started only with --enable-ndo and created a new contact, checked and the contact was there in mysql, but when I restarted the container, the contact wasn't there. I don't know if this is an issue with this container or with the mysql container used by your container.

**Comment by ethnchao** [comment]
Noticed, I will check that later.

**Comment by ethnchao** [comment]
@brunocantisano 
1. The Ndoutils will convert all current Nagios's data, like contacts, services definitions, and insert into MySQL DB.
2. When you visit Nagios/Adagios, the services status, contact status is from Nagios data file, NOT MySQL.
3. When you recreate new  Nagios container, the previous Nagios data file has been removed, so the Services & Contacts you created before is removed too, Ndoutils will now synchronize current status to MySQL DB.

**Comment by brunocantisano** [comment]
Hi,

Thanks for you quick answer.

I know that all data is removed when a container is removed, but when you
mount a volume the data is persisted. I can see that is persisted even if I
stop, remove and restart the mysql container. The contact that I created
appears in mysql, but when I start your container and link to the mysql
container, seems that the database is recreated.
So if I try to configure everything, stop and remove nagios container and
restart nagios container all database will be recreated. Is that right?

Thanks a lot to your support.
Bruno.

Em Qui, 12 de jul de 2018 08:22, ethnchao <notifications@github.com>
escreveu:

**Comment by ethnchao** [comment]
I just re-test the container's behavior:

1. first create nagios(with --enable-ndo --create-db options) and mysql container(empty database), so after the container started, NdoUtils did insert all the data into MySQL. 
2. Create a contact named: ethnchao(remember reload the nagios daemon on the Adagios page), check the database table: **nagios_contacts**, the contact is there, everything is fine.
3. Delete contact: ethnchao, check the database table: **nagios_contacts**, the contact has been removed.
4. Recreate the contact: ethnchao.
5. And then stop and remove the nagios container, recreate nagios(with --enable-ndo, and remember set the right environments: MYSQL_ADDRESS/MYSQL_DATABASE/MYSQL_USER/MYSQL_PASSWORD) container, now the nagios data is new, check the database table: **nagios_contacts**, there is no contact: ethnchao, because NdoUtils will synchronize current status of Nagios, BUT the database is not recreated, just erased the table's data.

When you recreate Nagios container, the nagios data will not be persisted, so NdoUtils will delete all the data from MySQL which not exist in Nagios. In the other way, the database is recreated. You're right.

My experience is: DO NOT delete the nagios container, when you have to do this, backup first.

And this docker-nagios is a rich-container, contains too many software, I can't provide a way like mysql: just mount a volume to /var/lib/mysql, so all the data will be retain.

**Comment by brunocantisano** [comment]
Hi,

Great help.

I'll put a step to backup the database when is stopped and a step to
restore the database when is started if the file exists.
When is working I'll submit a pull request. Thank you very much.



Em Qui, 12 de jul de 2018 23:46, ethnchao <notifications@github.com>
escreveu:

**Comment by dberardo-com** [comment]
> The Ndoutils will convert all current Nagios's data, like contacts, services definitions, and insert into MySQL DB.

then what do we need a database for? isnt it just redundant?

@ethnchao
